// leave off @2x/@3x
const images = {
  onboarding_selfcare: require('../images/onbording-self-care.png'),
  onboarding_tracking: require('../images/onbording-tracking.png'),
  userPlaceholder: require('../images/user-icon-placeholder.png'),
  noTalkStep1: require('../images/no-talk-step-1.png'),
  femaleIcon: require('../images/icons/female-symbol-icon.png'),
  maleIcon: require('../images/icons/male-symbol-icon.png'),
  animateHeart: require('../images/animate-heart.gif'),
  healtcareProfessionals: require('../images/healthcare-professionals.png'),
  normalPerson: require('../images/normal-person.png'),
  womenGender: require('../images/women.png'),
  menGender: require('../images/men.png'),
  menGenderAvatar: require('../images/men-avatar.png'),
  womenGenderAvatar: require('../images/women-avatar.png'),
  congratulations: require('../images/congratulations.png'),
  appCrash: require('../images/app-crash.png'),
  notCofee: require('../images/figures/no-drink-cofee.png'),
  chair: require('../images/figures/chair.png'),
  notSmoking: require('../images/figures/no-smoking.png'),
  notRunning: require('../images/figures/no-running.png'),
  welcome1: require('../images/welcome-1.gif'),
  'woman-checking-blood-pressure': require('../images/woman-checking-blood-pressure.png'),
  indeveloping: require('../images/transistor-page-under-construction.gif'),
  steps_take_bp: require('../images/pasos-toma-pa.jpeg'),
  businessMen: require('../images/illustrations/business-3d-businessman.png'),
  juicyWomanIsLooking: require('../images/gifs/juicy-woman-is-looking.gif'),
};

export default images;
